export default {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numRatings: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 80,
      brand: "Nike",
      rating: 4.5,
      numRatings: 10,
      countInStock: 5,
    },
    {
      _id: "3",
      name: "Best pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 250,
      brand: "Nike",
      rating: 4.5,
      numRatings: 10,
      countInStock: 2,
    },
    {
      _id: "4",
      name: "Slim Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 140,
      brand: "Nike",
      rating: 4.5,
      numRatings: 10,
      countInStock: 9,
    },
    {
      _id: "5",
      name: "Fit Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numRatings: 10,
      countInStock: 0,
    },
  ],
};
